# Generated by Django 3.1.3 on 2024-06-25 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=128)),
                ('profile', models.TextField()),
                ('picture', models.ImageField(blank=True, max_length=225, null=True, upload_to='enterprise/')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('member', models.ManyToManyField(related_name='member_enterprise', to='user.User')),
            ],
        ),
    ]
