# Generated by Django 5.0.6 on 2024-06-29 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=128)),
                ('profile', models.TextField(default='')),
                ('picture', models.ImageField(default='enterprise/default.jpg', max_length=225, upload_to='enterprise/')),
                ('address', models.TextField(default='')),
                ('fan', models.IntegerField(default=0)),
                ('fans', models.ManyToManyField(related_name='user_like_enterprise', to='Users.applicant')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.applicant')),
                ('member', models.ManyToManyField(related_name='member_enterprise', to='Users.applicant')),
            ],
            options={
                'db_table': 'enterprise_enterprise',
            },
        ),
    ]
