# Generated by Django 5.0.6 on 2024-06-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0001_initial'),
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='normal_user_material',
            field=models.ManyToManyField(related_name='normal_user_material', to='recruit.material'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='recruit_material',
            field=models.ManyToManyField(related_name='recruit_user_material', to='recruit.material'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='recruitment',
            field=models.ManyToManyField(related_name='recruitment_belong_enterprise', to='recruit.recruit'),
        ),
    ]
