# Generated by Django 3.1.3 on 2024-06-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='profile',
            field=models.TextField(default=''),
        ),
    ]
