# Generated by Django 3.1.3 on 2024-06-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_position'),
        ('enterprise', '0002_auto_20240625_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='member',
            field=models.ManyToManyField(related_name='member_enterprise', to='Users.Applicant'),
        ),
    ]
