# Generated by Django 4.2.4 on 2024-06-30 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0001_initial"),
        ("enterprise", "0003_remove_enterprise_normal_user_material_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserInformationEnterprise",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("post", models.CharField(default="", max_length=128)),
                ("join_data", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users.applicant",
                    ),
                ),
            ],
        ),
    ]
