# Generated by Django 3.1.3 on 2024-06-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_position'),
        ('enterprise', '0003_auto_20240625_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='fan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='fans',
            field=models.ManyToManyField(related_name='user_like_enterprise', to='Users.Applicant'),
        ),
    ]
