# Generated by Django 4.2.13 on 2024-06-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_auto_20240625_1719'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enterprise',
            table='enterprise_enterprise',
        ),
    ]
