# Generated by Django 4.2.13 on 2024-06-25 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0003_position"),
        ("enterprise", "0004_auto_20240625_1719"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="manager",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="Users.applicant"
            ),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="picture",
            field=models.ImageField(
                blank=True,
                default="enterprise/default.jpg",
                max_length=225,
                null=True,
                upload_to="enterprise/",
            ),
        ),
    ]
