# Generated by Django 4.2.4 on 2024-06-30 17:35

from django.db import migrations, models
import enterprise.models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0004_userinformationenterprise"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userinformationenterprise",
            old_name="join_data",
            new_name="join_date",
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="picture",
            field=models.ImageField(
                default="enterprise/default.jpg",
                max_length=225,
                upload_to=enterprise.models.custom_enterprise_picture_upload_to,
            ),
        ),
    ]
