# Generated by Django 4.2.4 on 2024-07-01 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "enterprise",
            "0005_rename_join_data_userinformationenterprise_join_date_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enterprise",
            name="fan",
        ),
    ]
