# Generated by Django 4.2.13 on 2024-06-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0005_alter_enterprise_manager_alter_enterprise_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="picture",
            field=models.ImageField(
                default="enterprise/default.jpg",
                max_length=225,
                upload_to="enterprise/",
            ),
        ),
    ]
