# Generated by Django 4.2.4 on 2024-06-26 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0006_alter_enterprise_picture"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="enterprise",
            table="enterprise_enterprise",
        ),
    ]
