# Generated by Django 4.2.4 on 2024-06-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0005_recruit_salary_high_recruit_salary_low"),
        ("enterprise", "0007_alter_enterprise_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprise",
            name="recruitment",
            field=models.ManyToManyField(
                related_name="recruitment_belong_enterprise", to="recruit.recruit"
            ),
        ),
    ]
