# Generated by Django 4.2.4 on 2024-06-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0005_recruit_salary_high_recruit_salary_low"),
        ("enterprise", "0008_enterprise_recruitment"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprise",
            name="normal_user_material",
            field=models.ManyToManyField(
                related_name="normal_user_material", to="recruit.material"
            ),
        ),
        migrations.AddField(
            model_name="enterprise",
            name="recruit_material",
            field=models.ManyToManyField(
                related_name="recruit_user_material", to="recruit.material"
            ),
        ),
    ]
