# Generated by Django 4.2.13 on 2024-06-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0005_alter_enterprise_table'),
        ('enterprise', '0009_enterprise_normal_user_material_and_more'),
    ]

    operations = [
    ]
