# Generated by Django 4.2.4 on 2024-06-29 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0018_alter_information_id"),
        ("enterprise", "0010_merge_20240627_0235"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="manager",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Users.applicant",
            ),
        ),
    ]
