# Generated by Django 4.2.13 on 2024-06-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0018_alter_information_id"),
        ("enterprise", "0011_alter_enterprise_manager"),
    ]

    operations = [
        migrations.AddField(
            model_name="enterprise",
            name="withdraw",
            field=models.ManyToManyField(
                related_name="withdraw_enterprise", to="Users.applicant"
            ),
        ),
    ]
