# Generated by Django 4.2.13 on 2024-06-30 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0012_enterprise_withdraw"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enterprise",
            name="normal_user_material",
        ),
    ]
