# Generated by Django 5.0.6 on 2024-06-29 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0)),
                ('recruit_id', models.IntegerField(default=0)),
                ('recruit_name', models.CharField(default='', max_length=128)),
            ],
            options={
                'db_table': 'applicant_interests',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('interests', models.CharField(default='', max_length=128)),
                ('background', models.CharField(default='', max_length=128)),
                ('note', models.FileField(default='person_note/default_note.txt', upload_to='person_note/')),
                ('enterprise_id', models.IntegerField(default=0)),
                ('manage_enterprise_id', models.IntegerField(default=0)),
                ('is_upload', models.BooleanField(default=False)),
                ('followers', models.ManyToManyField(related_name='following', to='Users.applicant')),
            ],
            options={
                'db_table': 'applicant_info',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=128, null=True)),
                ('phone', models.CharField(default='', max_length=30, null=True)),
                ('native_place', models.CharField(default='', max_length=128, null=True)),
                ('nationality', models.CharField(default='', max_length=128, null=True)),
                ('birthday', models.DateField(blank=True, default=None, null=True)),
                ('marriage', models.BooleanField(default=False, null=True)),
                ('gender', models.CharField(default='', max_length=30, null=True)),
                ('education', models.CharField(default='', max_length=30, null=True)),
                ('school', models.CharField(default='', max_length=128, null=True)),
                ('only_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.applicant')),
            ],
        ),
        migrations.AddField(
            model_name='applicant',
            name='only_information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.information'),
        ),
    ]
