# Generated by Django 3.2 on 2024-06-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('interests', models.CharField(default='', max_length=128)),
                ('background', models.CharField(default='', max_length=128)),
                ('note_path', models.TextField(default='')),
            ],
            options={
                'db_table': 'applicant_info',
            },
        ),
    ]
