# Generated by Django 4.2.4 on 2024-06-30 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "enterprise",
            "0005_rename_join_data_userinformationenterprise_join_date_and_more",
        ),
        ("recruit", "0002_alter_material_certificate_and_more"),
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="user_information_enterprise",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="enterprise.userinformationenterprise",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="user_material",
            field=models.ManyToManyField(
                related_name="user_all_material", to="recruit.material"
            ),
        ),
    ]
