# Generated by Django 3.2 on 2024-06-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='note_path',
        ),
        migrations.AddField(
            model_name='applicant',
            name='enterprise_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicant',
            name='manage_enterprise_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='applicant',
            name='note',
            field=models.FileField(default='person_note/default_note.txt', upload_to='person_note/'),
        ),
    ]
