# Generated by Django 4.2.4 on 2024-07-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "enterprise",
            "0005_rename_join_data_userinformationenterprise_join_date_and_more",
        ),
        ("Users", "0002_applicant_user_information_enterprise_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="user_follow_enterprise",
            field=models.ManyToManyField(
                related_name="user_follow_enterprise", to="enterprise.enterprise"
            ),
        ),
    ]
