# Generated by Django 3.2 on 2024-06-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20240625_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0)),
                ('recruit_id', models.IntegerField(default=0)),
                ('recruit_name', models.CharField(default='', max_length=128)),
            ],
            options={
                'db_table': 'applicant_interests',
            },
        ),
    ]
