# Generated by Django 4.2.13 on 2024-06-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='followers',
            field=models.ManyToManyField(related_name='following', to='Users.applicant'),
        ),
    ]
