# Generated by Django 3.2 on 2024-06-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_upload',
            field=models.BooleanField(default=False),
        ),
    ]
