# Generated by Django 4.2.4 on 2024-06-27 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_applicant_is_upload"),
    ]

    operations = [
        migrations.CreateModel(
            name="Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=128)),
                ("phone", models.CharField(default="", max_length=30)),
                ("native_place", models.CharField(default="", max_length=128)),
                ("nationality", models.CharField(default="", max_length=128)),
                ("birthday", models.DateField(blank=True, default=None, null=True)),
                ("marriage", models.BooleanField(default=False)),
                ("gender", models.CharField(default="", max_length=30)),
                ("education", models.CharField(default="", max_length=30)),
                ("school", models.CharField(default="", max_length=128)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users.applicant",
                    ),
                ),
            ],
        ),
    ]
