# Generated by Django 4.2.13 on 2024-06-26 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_applicant_followers'),
        ('Users', '0004_applicant_is_upload'),
    ]

    operations = [
    ]
