# Generated by Django 4.2.13 on 2024-06-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_merge_20240627_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='followers',
        ),
    ]
