# Generated by Django 4.2.13 on 2024-06-27 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_applicant_information'),
        ('Users', '0007_applicant_followers'),
    ]

    operations = [
    ]
