# Generated by Django 4.2.4 on 2024-06-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0009_remove_applicant_information_remove_information_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="information",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
