# Generated by Django 4.2.4 on 2024-06-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0010_alter_information_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="information",
            name="education",
            field=models.CharField(default="", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="information",
            name="gender",
            field=models.CharField(default="", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="information",
            name="marriage",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="information",
            name="name",
            field=models.CharField(default="", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="information",
            name="nationality",
            field=models.CharField(default="", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="information",
            name="native_place",
            field=models.CharField(default="", max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="information",
            name="phone",
            field=models.CharField(default="", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="information",
            name="school",
            field=models.CharField(default="", max_length=128, null=True),
        ),
    ]
