# Generated by Django 4.2.4 on 2024-06-28 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0011_alter_information_education_alter_information_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="only_information",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Users.information",
            ),
        ),
        migrations.AddField(
            model_name="information",
            name="only_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Users.applicant",
            ),
        ),
    ]
