# Generated by Django 4.2.4 on 2024-06-28 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0012_applicant_only_information_information_only_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicant",
            name="only_information",
        ),
    ]
