# Generated by Django 4.2.4 on 2024-06-28 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0011_remove_material_information"),
        ("Users", "0013_remove_applicant_only_information"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Information",
        ),
    ]
