# Generated by Django 4.2.4 on 2024-06-28 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0014_delete_information"),
    ]

    operations = [
        migrations.CreateModel(
            name="Information",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="", max_length=128, null=True)),
                ("phone", models.CharField(default="", max_length=30, null=True)),
                (
                    "native_place",
                    models.CharField(default="", max_length=128, null=True),
                ),
                (
                    "nationality",
                    models.CharField(default="", max_length=128, null=True),
                ),
                ("birthday", models.DateField(blank=True, default=None, null=True)),
                ("marriage", models.BooleanField(default=False, null=True)),
                ("gender", models.CharField(default="", max_length=30, null=True)),
                ("education", models.CharField(default="", max_length=30, null=True)),
                ("school", models.CharField(default="", max_length=128, null=True)),
                (
                    "only_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Users.applicant",
                    ),
                ),
            ],
        ),
    ]
