# Generated by Django 4.2.4 on 2024-06-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0007_alter_information_education_alter_information_gender_and_more"),
        ("Users", "0016_applicant_only_information"),
    ]

    operations = []
