# Generated by Django 4.2.4 on 2024-06-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0017_merge_20240629_2022"),
    ]

    operations = [
        migrations.AlterField(
            model_name="information",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
