# Generated by Django 5.0.6 on 2024-06-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(1, '点赞通知'), (2, '评论通知'), (3, '关注通知'), (4, '企业通知'), (5, '员工退出企业通知')])),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('related_user_id', models.IntegerField(blank=True, null=True)),
                ('related_blog_id', models.IntegerField(blank=True, null=True)),
                ('related_enterprise_id', models.IntegerField(blank=True, null=True)),
                ('attachment', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
