# Generated by Django 5.0.6 on 2024-06-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_attachment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='related_enterprise_id',
            new_name='related_recruitment_id',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[(1, '点赞通知'), (2, '评论通知'), (3, '关注通知'), (4, '企业通知'), (5, '员工退出企业通知'), (6, '员工同意/拒绝企业通知')]),
        ),
    ]
