# Generated by Django 3.2 on 2024-06-28 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trend_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('content', models.TextField(default='')),
            ],
            options={
                'db_table': 'trend_comments',
            },
        ),
        migrations.CreateModel(
            name='Dynamic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default=0)),
                ('content', models.TextField(default='')),
                ('type', models.CharField(default='', max_length=128)),
                ('send_date', models.DateTimeField(default=datetime.datetime.now)),
                ('transpond_id', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('comment_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'applicant_trends',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trend_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'trend_likes',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trend_id', models.IntegerField(default=0)),
                ('recruit_name', models.CharField(default='', max_length=128)),
            ],
            options={
                'db_table': 'trend_tags',
            },
        ),
    ]
