# Generated by Django 3.2 on 2024-06-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Trend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dynamic',
            old_name='comment_id',
            new_name='comment_count',
        ),
    ]
