# Generated by Django 3.2 on 2024-06-29 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trend', '0002_rename_comment_id_dynamic_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='send_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
