# Generated by Django 3.2 on 2024-06-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trend', '0003_comment_send_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendPicture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trend_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
                ('picture', models.ImageField(default='trend_pic/default.jpg', max_length=225, upload_to='trend_pic/')),
            ],
            options={
                'db_table': 'trend_pictures',
            },
        ),
    ]
