# Generated by Django 3.2 on 2024-06-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.FileField(default='llm_note/default_note.txt', upload_to='llm_note/')),
            ],
            options={
                'db_table': 'llm_file',
            },
        ),
    ]
