# Generated by Django 3.1.3 on 2024-06-25 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('enterprise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post', models.CharField(default='', max_length=128)),
                ('profile', models.TextField(default='')),
                ('number', models.IntegerField(default=0)),
                ('release_time', models.DateField(auto_now_add=True)),
                ('education', models.CharField(default='', max_length=30)),
                ('employment', models.ManyToManyField(related_name='employment_recruit_user', to='user.User')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterprise.enterprise')),
                ('user_application', models.ManyToManyField(related_name='application_recruit_user', to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=128)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=30)),
                ('native_place', models.CharField(default='', max_length=128)),
                ('nationality', models.CharField(default='', max_length=128)),
                ('birthday', models.DateField(blank=True, default=None, null=True)),
                ('marriage', models.BooleanField(default=False)),
                ('gender', models.CharField(default='', max_length=30)),
                ('education', models.CharField(default='', max_length=30)),
                ('school', models.CharField(default='', max_length=128)),
                ('curriculum_vitae', models.FileField(upload_to='material_curriculum/')),
                ('certificate', models.FileField(upload_to='certificate/')),
                ('Recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.recruit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
