# Generated by Django 4.2.4 on 2024-06-30 17:35

from django.db import migrations, models
import recruit.models


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="certificate",
            field=models.FileField(
                blank=True, upload_to=recruit.models.custom_certificate_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="curriculum_vitae",
            field=models.FileField(
                blank=True, upload_to=recruit.models.custom_vitae_upload_to
            ),
        ),
    ]
