# Generated by Django 3.1.3 on 2024-06-25 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_position'),
        ('recruit', '0002_auto_20240625_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='Recruit',
            new_name='recruit',
        ),
        migrations.AlterField(
            model_name='material',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.applicant'),
        ),
    ]
