# Generated by Django 4.2.4 on 2024-07-01 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0002_alter_material_certificate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recruit",
            name="user_material",
        ),
    ]
