# Generated by Django 3.1.3 on 2024-06-25 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_auto_20240625_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='certificate',
            field=models.FileField(blank=True, upload_to='certificate/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='curriculum_vitae',
            field=models.FileField(blank=True, upload_to='material_curriculum/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='recruit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recruit.recruit'),
        ),
        migrations.AlterField(
            model_name='material',
            name='status',
            field=models.CharField(default='3', max_length=20),
        ),
    ]
