# Generated by Django 4.2.4 on 2024-06-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0004_auto_20240625_2205"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruit",
            name="salary_high",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="recruit",
            name="salary_low",
            field=models.IntegerField(default=0),
        ),
    ]
