# Generated by Django 4.2.4 on 2024-06-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0005_recruit_salary_high_recruit_salary_low"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruit",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
