# Generated by Django 4.2.13 on 2024-06-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0006_recruit_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruit",
            name="address",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="recruit",
            name="experience",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AddField(
            model_name="recruit",
            name="requirement",
            field=models.TextField(default=""),
        ),
    ]
