# Generated by Django 4.2.4 on 2024-06-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0007_recruit_address_recruit_experience_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruit",
            name="education",
            field=models.CharField(default="无要求", max_length=30),
        ),
        migrations.AlterField(
            model_name="recruit",
            name="experience",
            field=models.CharField(default="无要求", max_length=128),
        ),
        migrations.AlterField(
            model_name="recruit",
            name="requirement",
            field=models.TextField(default="无要求"),
        ),
    ]
