# Generated by Django 4.2.4 on 2024-06-27 02:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("enterprise", "0009_enterprise_normal_user_material_and_more"),
        ("recruit", "0008_alter_recruit_education_alter_recruit_experience_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="birthday",
        ),
        migrations.RemoveField(
            model_name="material",
            name="education",
        ),
        migrations.RemoveField(
            model_name="material",
            name="email",
        ),
        migrations.RemoveField(
            model_name="material",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="material",
            name="marriage",
        ),
        migrations.RemoveField(
            model_name="material",
            name="name",
        ),
        migrations.RemoveField(
            model_name="material",
            name="nationality",
        ),
        migrations.RemoveField(
            model_name="material",
            name="native_place",
        ),
        migrations.RemoveField(
            model_name="material",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="material",
            name="school",
        ),
        migrations.RemoveField(
            model_name="material",
            name="user",
        ),
        migrations.AddField(
            model_name="material",
            name="enterprise",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="enterprise.enterprise",
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="submit_time",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
