# Generated by Django 4.2.4 on 2024-06-28 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruit", "0010_material_information"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="information",
        ),
    ]
