# Generated by Django 4.2.4 on 2024-06-28 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0016_applicant_only_information"),
        ("recruit", "0011_remove_material_information"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="information",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Users.information",
            ),
        ),
    ]
