# Generated by Django 3.1.3 on 2024-06-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='0', max_length=128),
        ),
    ]
