# Generated by Django 4.2.13 on 2024-06-25 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_application_status'),
        ('manager', '0005_auto_20240625_1126'),
    ]

    operations = [
    ]
