# Generated by Django 3.1.3 on 2024-06-25 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20240625_1126'),
        ('manager', '0005_alter_application_status'),
    ]

    operations = [
    ]
