# Generated by Django 4.2.13 on 2024-06-26 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_merge_20240625_1504'),
        ('manager', '0006_merge_20240625_1704'),
    ]

    operations = [
    ]
