# Generated by Django 4.2.4 on 2024-06-26 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager", "0006_merge_20240625_1504"),
        ("manager", "0006_merge_20240625_1704"),
    ]

    operations = []
