# Generated by Django 4.2.13 on 2024-06-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_merge_20240626_1416'),
        ('manager', '0007_merge_20240626_1554'),
    ]

    operations = [
    ]
